(function(){'use strict';
var e="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},h="object"===typeof e.global&&e.global?e.global:"object"===typeof global&&global&&global.Object===Object?global:this;e.global=h;var m="object"===typeof e.exportsNamespace&&e.exportsNamespace?e.exportsNamespace:h;e.exportsNamespace=m;h.Object.freeze(e);var aa={envInfo:e,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.14"};h.Object.freeze(aa);h.Object.freeze(aa.semantics);
var ba=h.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},n=h.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},p=0,q=h.WeakMap?new h.WeakMap:null;function r(a){return function(b,c){return!(!b||!b.a||b.a.m!==c||b.a.k!==a)}}function ca(a){for(var b in a)return b}
function da(a,b,c){var d=new a.G(b[c]);if(c<b.length-1){a=a.o;c+=1;for(var g=d.E,f=0;f<g.length;f++)g[f]=da(a,b,c)}return d}function ea(a){return void 0===a?"undefined":a.toString()}
function fa(a){switch(typeof a){case "string":return t(ga);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?t(ha):b<<16>>16===b&&1/b!==1/-0?t(ia):t(ja):"number"===typeof a?t(ka):t(la);case "boolean":return t(ma);case "undefined":return t(na);default:return null===a?a.pa():a&&a.a&&a.a.h.D?t(oa):a&&a.a?t(a.a):null}}
function pa(a){switch(typeof a){case "string":qa||(qa=(new v).c());for(var b=0,c=1,d=-1+(a.length|0)|0;0<=d;)b=b+ba(65535&(a.charCodeAt(d)|0),c)|0,c=ba(31,c),d=-1+d|0;return b;case "number":w||(w=(new x).c());b=w;c=a|0;if(c===a&&-Infinity!==1/a)b=c;else{if(b.i)b.J[0]=a,b=y(b.v[b.M]|0,b.v[b.K]|0);else{if(a!==a)b=!1,a=2047,c=+h.Math.pow(2,51);else if(Infinity===a||-Infinity===a)b=0>a,a=2047,c=0;else if(0===a)b=-Infinity===1/a,c=a=0;else if(d=(b=0>a)?-a:a,d>=+h.Math.pow(2,-1022)){a=+h.Math.pow(2,52);
var c=+h.Math.log(d)/.6931471805599453,c=+h.Math.floor(c)|0,c=1023>c?c:1023,g=d/+h.Math.pow(2,c)*a,d=+h.Math.floor(g),g=g-d,d=.5>g?d:.5<g?1+d:0!==d%2?1+d:d;2<=d/a&&(c=1+c|0,d=1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=a);a=c;c=d}else a=d/+h.Math.pow(2,-1074),c=+h.Math.floor(a),d=a-c,a=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c;c=+c;b=y(c|0,(b?-2147483648:0)|(a|0)<<20|c/4294967296|0)}b=b.w^b.u}return b;case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.C():null===q?42:
ra(a)}}function sa(a,b){var c=h.Object.getPrototypeOf,d=h.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function ta(a,b,c){a=sa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function ua(a,b,c,d){a=sa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new h.TypeError("super has no setter '"+c+"'.");}
var ra=null!==q?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return pa(a);default:if(null===a)return 0;var b=q.get(a);void 0===b&&(p=b=p+1|0,q.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(h.Object.isSealed(a))return 42;p=b=p+1|0;return a.$idHashCode$0=b}return null===a?0:pa(a)};this.__ScalaJSExportsNamespace=m;
function z(){this.y=this.G=void 0;this.k=this.o=this.h=null;this.m=0;this.F=null;this.t="";this.d=this.r=this.s=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function A(a,b,c){var d=new z;d.h={};d.o=null;d.F=a;d.t=b;d.d=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function B(a,b,c,d,g,f,l){var k=new z,u=ca(a);f=f||function(a){return!!(a&&a.a&&a.a.h[u])};l=l||function(a,b){return!!(a&&a.a&&a.a.m===b&&a.a.k.h[u])};k.y=g;k.h=c;k.t="L"+b+";";k.d=l;k.name=b;k.isInterface=!1;k.isRawJSType=!!d;k.isInstance=f;return k}
function wa(a){function b(a){if("number"===typeof a){this.E=Array(a);for(var b=0;b<a;b++)this.E[b]=g}else this.E=a}var c=new z,d=a.F,g="longZero"==d?C().A:d;b.prototype=new D;b.prototype.constructor=b;b.prototype.a=c;var d="["+a.t,f=a.k||a,l=a.m+1;c.G=b;c.y=xa;c.h={b:1,sa:1,e:1};c.o=a;c.k=f;c.m=l;c.F=null;c.t=d;c.s=void 0;c.r=void 0;c.d=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return f.d(a,l)};return c}
function t(a){if(!a.s){var b=new E;b.p=a;a.s=b}return a.s}z.prototype.getFakeInstance=function(){return this===ga?"some string":this===ma?!1:this===ha||this===ia||this===ja||this===ka||this===la?0:this===oa?C().A:this===na?void 0:{a:this}};z.prototype.getSuperclass=function(){return this.y?t(this.y):null};z.prototype.getComponentType=function(){return this.o?t(this.o):null};z.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b.r||(b.r=wa(b)),b=b.r;return da(b,a,0)};
var ya=A(!1,"Z","boolean"),za=A(0,"C","char"),Aa=A(0,"B","byte"),Ba=A(0,"S","short"),Ca=A(0,"I","int"),Da=A("longZero","J","long"),Ea=A(0,"F","float"),Fa=A(0,"D","double");ya.d=r(ya);za.d=r(za);Aa.d=r(Aa);Ba.d=r(Ba);Ca.d=r(Ca);Da.d=r(Da);Ea.d=r(Ea);Fa.d=r(Fa);function F(){}function D(){}D.prototype=F.prototype;F.prototype.c=function(){return this};F.prototype.z=function(){var a=fa(this).p.name,b=(+(this.C()>>>0)).toString(16);return a+"@"+b};F.prototype.C=function(){return ra(this)};F.prototype.toString=function(){return this.z()};var xa=B({b:0},"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.a){var c=a.m||0;return!(c<b)&&(c>b||!a.k.isPrimitive)}return!1});F.prototype.a=xa;
function G(){this.H=this.O=null;this.f=0}G.prototype=new D;G.prototype.constructor=G;G.prototype.c=function(){return this};function H(){var a;I||(I=(new G).c());a=I;0===(268435456&a.f)&&0===(268435456&a.f)&&(0===(134217728&a.f)&&0===(134217728&a.f)&&(a.O=h,a.f|=134217728),a.H=a.O.document,a.f|=268435456);return a.H}G.prototype.a=B({T:0},"org.scalajs.dom.package$",{T:1,b:1});var I=void 0;function E(){this.p=null}E.prototype=new D;E.prototype.constructor=E;
E.prototype.z=function(){return(this.p.isInterface?"interface ":this.p.isPrimitive?"":"class ")+this.p.name};E.prototype.a=B({Z:0},"java.lang.Class",{Z:1,b:1});function J(){this.I=this.N=null}J.prototype=new D;J.prototype.constructor=J;J.prototype.c=function(){K=this;this.N=Ga(!1);this.I=Ga(!0);return this};J.prototype.a=B({ga:0},"java.lang.System$",{ga:1,b:1});var K=void 0;function Ha(){K||(K=(new J).c());return K}function L(){}L.prototype=new D;L.prototype.constructor=L;function Ia(){}
Ia.prototype=L.prototype;function M(){this.q=null}M.prototype=new D;M.prototype.constructor=M;M.prototype.z=function(){return"DynamicVariable("+this.q+")"};function N(a,b){a.q=b;return a}M.prototype.a=B({ia:0},"scala.util.DynamicVariable",{ia:1,b:1});function x(){this.i=!1;this.J=this.v=this.l=null;this.B=!1;this.M=this.K=0}x.prototype=new D;x.prototype.constructor=x;
x.prototype.c=function(){w=this;this.l=(this.i=!!(h.ArrayBuffer&&h.Int32Array&&h.Float32Array&&h.Float64Array))?new h.ArrayBuffer(8):null;this.v=this.i?new h.Int32Array(this.l,0,2):null;this.i&&new h.Float32Array(this.l,0,2);this.J=this.i?new h.Float64Array(this.l,0,1):null;if(this.i)this.v[0]=16909060,a=1===((new h.Int8Array(this.l,0,8))[0]|0);else var a=!0;this.K=(this.B=a)?0:1;this.M=this.B?1:0;return this};x.prototype.a=B({ja:0},"scala.scalajs.runtime.Bits$",{ja:1,b:1});var w=void 0;
function v(){this.f=!1}v.prototype=new D;v.prototype.constructor=v;v.prototype.c=function(){return this};v.prototype.a=B({la:0},"scala.scalajs.runtime.RuntimeString$",{la:1,b:1});var qa=void 0;function O(){}O.prototype=new D;O.prototype.constructor=O;O.prototype.c=function(){return this};
O.prototype.main=function(){var a=ea(H().body);Ja(Ka().x.q,a+"\n");a=H().body;-1!==(ea(a).indexOf("http://schema.org/Recipe")|0)?(H().body,Ja(Ka().x.q,"Hooray! This looks like a recipe!!!\n")):(H().body,Ja(Ka().x.q,"This is not a recipe :(\n"))};O.prototype.a=B({P:0},"com.schwartz.scraper.Scraper$",{P:1,b:1,wa:1});var La=void 0;m.com=m.com||{};m.com.schwartz=m.com.schwartz||{};m.com.schwartz.scraper=m.com.schwartz.scraper||{};m.com.schwartz.scraper.Scraper=function(){La||(La=(new O).c());return La};
function P(){}P.prototype=new D;P.prototype.constructor=P;function Ma(){}Ma.prototype=P.prototype;var na=B({ma:0},"scala.runtime.BoxedUnit",{ma:1,b:1,e:1},void 0,void 0,function(a){return void 0===a});function Q(){}Q.prototype=new D;Q.prototype.constructor=Q;function Na(){}Na.prototype=Q.prototype;var ma=B({X:0},"java.lang.Boolean",{X:1,b:1,e:1,g:1},void 0,void 0,function(a){return"boolean"===typeof a});function R(){this.x=null}R.prototype=new Ia;R.prototype.constructor=R;
R.prototype.c=function(){S=this;this.x=N(new M,Ha().N);N(new M,Ha().I);N(new M,null);return this};R.prototype.a=B({ha:0},"scala.Console$",{ha:1,ta:1,b:1,va:1});var S=void 0;function Ka(){S||(S=(new R).c());return S}function T(){this.A=null}T.prototype=new D;T.prototype.constructor=T;T.prototype.c=function(){U=this;this.A=y(0,0);return this};
function Pa(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+n(1E9)|0)-(0!==b?n(b):32+n(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,f=a,l=b;for(a=b=0;0<=c&&0!==(-2097152&l);){var k=f,u=l,Oa=g,va=d;if(u===va?(-2147483648^k)>=(-2147483648^Oa):(-2147483648^u)>=(-2147483648^va))k=l,u=d,l=f-g|0,k=(-2147483648^l)>(-2147483648^f)?-1+(k-u|0)|0:k-u|0,f=l,l=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=d>>>1|0;g=g>>>1|0|d<<31;d=k}c=l;if(0===c?-1147483648<=(-2147483648^
f):-2147483648<=(-2147483648^c))c=4294967296*l+ +(f>>>0),f=c/1E9,g=f/4294967296|0,d=b,b=f=d+(f|0)|0,a=(-2147483648^f)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,f=c%1E9|0;c=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}T.prototype.a=B({ka:0},"scala.scalajs.runtime.RuntimeLong$",{ka:1,b:1,ua:1,e:1});var U=void 0;function C(){U||(U=(new T).c());return U}function V(){}V.prototype=new Na;V.prototype.constructor=V;function Qa(){}Qa.prototype=V.prototype;V.prototype.V=function(){return this};
var ga=B({U:0},"java.lang.String",{U:1,b:1,e:1,ra:1,g:1},void 0,void 0,function(a){return"string"===typeof a}),ha=B({Y:0},"java.lang.Byte",{Y:1,j:1,b:1,e:1,g:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),la=B({$:0},"java.lang.Double",{$:1,j:1,b:1,e:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),ka=B({aa:0},"java.lang.Float",{aa:1,j:1,b:1,e:1,g:1},void 0,void 0,function(a){return"number"===typeof a}),ja=B({ba:0},"java.lang.Integer",{ba:1,j:1,b:1,e:1,g:1},void 0,void 0,
function(a){return(a|0)===a&&1/a!==1/-0});function W(){}W.prototype=new Na;W.prototype.constructor=W;W.prototype.c=function(){return this};W.prototype.a=B({da:0},"java.lang.JSConsoleBasedPrintStream$DummyOutputStream",{da:1,S:1,b:1,Q:1,R:1});var oa=B({ea:0},"java.lang.Long",{ea:1,j:1,b:1,e:1,g:1},void 0,void 0,function(a){return!!(a&&a.a&&a.a.h.D)}),ia=B({fa:0},"java.lang.Short",{fa:1,j:1,b:1,e:1,g:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function X(){this.u=this.w=0}
X.prototype=new Ma;X.prototype.constructor=X;X.prototype.z=function(){C();var a=this.w,b=this.u;return b===a>>31?""+a:0>b?"-"+Pa(-a|0,0!==a?~b:-b|0):Pa(a,b)};function y(a,b){var c=new X;c.w=a;c.u=b;return c}X.prototype.C=function(){return this.w^this.u};X.prototype.a=B({D:0},"scala.scalajs.runtime.RuntimeLong",{D:1,j:1,b:1,e:1,g:1});function Y(){}Y.prototype=new Qa;Y.prototype.constructor=Y;function Ra(){}Ra.prototype=Y.prototype;Y.prototype.W=function(){V.prototype.V.call(this);return this};
function Z(){this.n=this.L=null}Z.prototype=new Ra;Z.prototype.constructor=Z;function Ga(a){var b=new Z;b.L=a;(new W).c();Y.prototype.W.call(b);b.n="";return b}function Ja(a,b){for(;""!==b;){var c=b.indexOf("\n")|0;if(0>c)a.n=""+a.n+b,b="";else{var d=""+a.n+b.substring(0,c);h.console&&(a.L&&h.console.error?h.console.error(d):h.console.log(d));a.n="";b=b.substring(1+c|0)}}}Z.prototype.a=B({ca:0},"java.lang.JSConsoleBasedPrintStream",{ca:1,oa:1,na:1,S:1,b:1,Q:1,R:1,qa:1});
}).call(this);
//# sourceMappingURL=recipe-scraper-opt.js.map
