(function(){'use strict';
var f,h="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},l="object"===typeof h.global&&h.global?h.global:"object"===typeof global&&global&&global.Object===Object?global:this;h.global=l;var n="object"===typeof h.exportsNamespace&&h.exportsNamespace?h.exportsNamespace:l;h.exportsNamespace=n;l.Object.freeze(h);var aa={envInfo:h,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.14"};l.Object.freeze(aa);l.Object.freeze(aa.semantics);
var p=l.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ba=l.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},ca=0,da=l.WeakMap?new l.WeakMap:null;function q(a){return function(b,c){return!(!b||!b.b||b.b.U!==c||b.b.S!==a)}}function ea(a){for(var b in a)return b}
function r(a,b){return fa(a,b,0)}function fa(a,b,c){var d=new a.Na(b[c]);if(c<b.length-1){a=a.W;c+=1;for(var g=d.a,k=0;k<g.length;k++)g[k]=fa(a,b,c)}return d}function ga(a){return void 0===a?"undefined":a.toString()}
function ha(a){switch(typeof a){case "string":return v(ia);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?v(ja):b<<16>>16===b&&1/b!==1/-0?v(ka):v(la):"number"===typeof a?v(ma):v(na);case "boolean":return v(oa);case "undefined":return v(pa);default:return null===a?a.Uc():qa(a)?v(ra):a&&a.b?v(a.b):null}}
function sa(a){switch(typeof a){case "string":return ta(ua(),a);case "number":return va(wa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.b||null===a?a.F():null===da?42:xa(a)}}function ya(a,b){var c=l.Object.getPrototypeOf,d=l.Object.getOwnPropertyDescriptor;for(a=c(a);null!==a;){var g=d(a,b);if(void 0!==g)return g;a=c(a)}}function za(a,b,c){a=ya(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}
function Aa(a,b,c,d){a=ya(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new l.TypeError("super has no setter '"+c+"'.");}
var xa=null!==da?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return sa(a);default:if(null===a)return 0;var b=da.get(a);void 0===b&&(ca=b=ca+1|0,da.set(a,b));return b}}:function(a){if(a&&a.b){var b=a.$idHashCode$0;if(void 0!==b)return b;if(l.Object.isSealed(a))return 42;ca=b=ca+1|0;return a.$idHashCode$0=b}return null===a?0:sa(a)};this.__ScalaJSExportsNamespace=n;
function w(){this.ra=this.Na=void 0;this.S=this.W=this.u=null;this.U=0;this.Ja=null;this.ka="";this.r=this.ha=this.ia=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function x(a,b,c){var d=new w;d.u={};d.W=null;d.Ja=a;d.ka=b;d.r=function(){return!1};d.name=c;d.isPrimitive=!0;d.isInstance=function(){return!1};return d}
function y(a,b,c,d,g,k,m){var t=new w,e=ea(a);k=k||function(a){return!!(a&&a.b&&a.b.u[e])};m=m||function(a,b){return!!(a&&a.b&&a.b.U===b&&a.b.S.u[e])};t.ra=g;t.u=c;t.ka="L"+b+";";t.r=m;t.name=b;t.isInterface=!1;t.isRawJSType=!!d;t.isInstance=k;return t}
function Ba(a){function b(a){if("number"===typeof a){this.a=Array(a);for(var b=0;b<a;b++)this.a[b]=g}else this.a=a}var c=new w,d=a.Ja,g="longZero"==d?z().ga:d;b.prototype=new A;b.prototype.constructor=b;b.prototype.b=c;var d="["+a.ka,k=a.S||a,m=a.U+1;c.Na=b;c.ra=B;c.u={d:1,Kb:1,h:1};c.W=a;c.S=k;c.U=m;c.Ja=null;c.ka=d;c.ia=void 0;c.ha=void 0;c.r=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return k.r(a,m)};return c}
function v(a){if(!a.ia){var b=new C;b.la=a;a.ia=b}return a.ia}function D(a){a.ha||(a.ha=Ba(a));return a.ha}w.prototype.getFakeInstance=function(){return this===ia?"some string":this===oa?!1:this===ja||this===ka||this===la||this===ma||this===na?0:this===ra?z().ga:this===pa?void 0:{b:this}};w.prototype.getSuperclass=function(){return this.ra?v(this.ra):null};w.prototype.getComponentType=function(){return this.W?v(this.W):null};
w.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=D(b);return r(b,a)};var Ca=x(!1,"Z","boolean"),Da=x(0,"C","char"),Ea=x(0,"B","byte"),Fa=x(0,"S","short"),Ga=x(0,"I","int"),Ha=x("longZero","J","long"),Ia=x(0,"F","float"),Ja=x(0,"D","double");Ca.r=q(Ca);Da.r=q(Da);Ea.r=q(Ea);Fa.r=q(Fa);Ga.r=q(Ga);Ha.r=q(Ha);Ia.r=q(Ia);Ja.r=q(Ja);function E(){}function A(){}A.prototype=E.prototype;E.prototype.c=function(){return this};E.prototype.s=function(){var a=G(ha(this)),b=(+(this.F()>>>0)).toString(16);return a+"@"+b};E.prototype.F=function(){return xa(this)};E.prototype.toString=function(){return this.s()};var B=y({d:0},"java.lang.Object",{d:1},void 0,void 0,function(a){return null!==a},function(a,b){if(a=a&&a.b){var c=a.U||0;return!(c<b)&&(c>b||!a.S.isPrimitive)}return!1});E.prototype.b=B;
function H(a){var b=r(D(B),[a.a.length]),c=a.a.length;a=a.a;var d=b.a;if(a!==d||0>0+c)for(var g=0;g<c;g++)d[0+g]=a[0+g];else for(g=c-1;0<=g;g--)d[0+g]=a[0+g];return b}
function Ka(a,b,c){if(32>c)return a.k().a[31&b];if(1024>c)return a.e().a[31&b>>5].a[31&b];if(32768>c)return a.f().a[31&b>>10].a[31&b>>5].a[31&b];if(1048576>c)return a.g().a[31&b>>15].a[31&b>>10].a[31&b>>5].a[31&b];if(33554432>c)return a.m().a[31&b>>20].a[31&b>>15].a[31&b>>10].a[31&b>>5].a[31&b];if(1073741824>c)return a.x().a[31&b>>25].a[31&b>>20].a[31&b>>15].a[31&b>>10].a[31&b>>5].a[31&b];throw(new I).c();}
function La(a,b,c){if(32<=c)if(1024>c)a.j(a.e().a[31&b>>5]);else if(32768>c)a.i(a.f().a[31&b>>10]),a.j(a.e().a[31&b>>5]);else if(1048576>c)a.l(a.g().a[31&b>>15]),a.i(a.f().a[31&b>>10]),a.j(a.e().a[31&b>>5]);else if(33554432>c)a.n(a.m().a[31&b>>20]),a.l(a.g().a[31&b>>15]),a.i(a.f().a[31&b>>10]),a.j(a.e().a[31&b>>5]);else if(1073741824>c)a.w(a.x().a[31&b>>25]),a.n(a.m().a[31&b>>20]),a.l(a.g().a[31&b>>15]),a.i(a.f().a[31&b>>10]),a.j(a.e().a[31&b>>5]);else throw(new I).c();}
function Ma(a,b,c){a.D(c);c=-1+c|0;switch(c){case -1:break;case 0:a.j(b.k());break;case 1:a.i(b.e());a.j(b.k());break;case 2:a.l(b.f());a.i(b.e());a.j(b.k());break;case 3:a.n(b.g());a.l(b.f());a.i(b.e());a.j(b.k());break;case 4:a.w(b.m());a.n(b.g());a.l(b.f());a.i(b.e());a.j(b.k());break;case 5:a.Z(b.x());a.w(b.m());a.n(b.g());a.l(b.f());a.i(b.e());a.j(b.k());break;default:throw(new J).oa(c);}}function Na(){this.eb=this.Ab=null;this.A=0}Na.prototype=new A;Na.prototype.constructor=Na;
Na.prototype.c=function(){return this};function Oa(a){0===(134217728&a.A)&&0===(134217728&a.A)&&(a.Ab=l,a.A|=134217728);return a.Ab}Na.prototype.b=y({Cb:0},"org.scalajs.dom.package$",{Cb:1,d:1});var Pa=void 0;function Qa(){Pa||(Pa=(new Na).c());return Pa}function C(){this.la=null}C.prototype=new A;C.prototype.constructor=C;function G(a){return a.la.name}C.prototype.s=function(){return(this.la.isInterface?"interface ":this.la.isPrimitive?"":"class ")+G(this)};
C.prototype.b=y({Jb:0},"java.lang.Class",{Jb:1,d:1});function Ra(){}Ra.prototype=new A;Ra.prototype.constructor=Ra;function Sa(){}Sa.prototype=Ra.prototype;function Ta(a,b){b=p(-862048943,b);b=p(461845907,b<<15|b>>>17|0);a^=b;return-430675100+p(5,a<<13|a>>>19|0)|0}function Ua(a){a=p(-2048144789,a^(a>>>16|0));a=p(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}
function Va(a,b,c){var d=(new K).aa(0);c=(new K).aa(c);b.na(Wa(function(a,b,c){return function(a){c.q=Ta(c.q,Xa(Ya(),a));b.q=1+b.q|0}}(a,d,c)));return Ua(c.q^d.q)}function Za(){this.fb=null}Za.prototype=new A;Za.prototype.constructor=Za;Za.prototype.c=function(){$a=this;this.fb=(new L).c();return this};Za.prototype.b=y({nc:0},"scala.collection.Iterator$",{nc:1,d:1});var $a=void 0;
function ab(a,b,c,d,g){var k=bb();cb(b.t,c);a.na(Wa(function(a,b,c,d){return function(a){if(d.q)db(b,a),d.q=!1;else return cb(b.t,c),db(b,a)}}(a,b,d,k)));cb(b.t,g);return b}function eb(){}eb.prototype=new A;eb.prototype.constructor=eb;function fb(){}fb.prototype=eb.prototype;function gb(){this.I=!1;this.ib=this.qa=this.T=null;this.va=!1;this.mb=this.jb=0}gb.prototype=new A;gb.prototype.constructor=gb;
gb.prototype.c=function(){hb=this;this.T=(this.I=!!(l.ArrayBuffer&&l.Int32Array&&l.Float32Array&&l.Float64Array))?new l.ArrayBuffer(8):null;this.qa=this.I?new l.Int32Array(this.T,0,2):null;this.I&&new l.Float32Array(this.T,0,2);this.ib=this.I?new l.Float64Array(this.T,0,1):null;if(this.I)this.qa[0]=16909060,a=1===((new l.Int8Array(this.T,0,8))[0]|0);else var a=!0;this.jb=(this.va=a)?0:1;this.mb=this.va?1:0;return this};
function va(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.I)a.ib[0]=b,a=(new M).E(a.qa[a.mb]|0,a.qa[a.jb]|0);else{if(b!==b)a=!1,b=2047,c=+l.Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var d=(a=0>b)?-b:b;if(d>=+l.Math.pow(2,-1022)){b=+l.Math.pow(2,52);var c=+l.Math.log(d)/.6931471805599453,c=+l.Math.floor(c)|0,c=1023>c?c:1023,g=d/+l.Math.pow(2,c)*b,d=+l.Math.floor(g),g=g-d,d=.5>g?d:.5<g?1+d:0!==d%2?1+d:d;2<=d/b&&(c=1+c|0,d=
1);1023<c?(c=2047,d=0):(c=1023+c|0,d-=b);b=c;c=d}else b=d/+l.Math.pow(2,-1074),c=+l.Math.floor(b),d=b-c,b=0,c=.5>d?c:.5<d?1+c:0!==c%2?1+c:c}c=+c;a=(new M).E(c|0,(a?-2147483648:0)|(b|0)<<20|c/4294967296|0)}return a.o^a.K}gb.prototype.b=y({Mc:0},"scala.scalajs.runtime.Bits$",{Mc:1,d:1});var hb=void 0;function wa(){hb||(hb=(new gb).c());return hb}function ib(){this.A=!1}ib.prototype=new A;ib.prototype.constructor=ib;ib.prototype.c=function(){return this};
function ta(a,b){a=0;for(var c=1,d=-1+(b.length|0)|0;0<=d;)a=a+p(65535&(b.charCodeAt(d)|0),c)|0,c=p(31,c),d=-1+d|0;return a}ib.prototype.b=y({Oc:0},"scala.scalajs.runtime.RuntimeString$",{Oc:1,d:1});var jb=void 0;function ua(){jb||(jb=(new ib).c());return jb}function kb(){}kb.prototype=new A;kb.prototype.constructor=kb;kb.prototype.c=function(){return this};function lb(a,b){return b&&b.b&&b.b.u.Ha?b.J:b}function mb(a,b){return b&&b.b&&b.b.u.N?b:(new nb).oa(b)}
kb.prototype.b=y({Pc:0},"scala.scalajs.runtime.package$",{Pc:1,d:1});var ob=void 0;function pb(){ob||(ob=(new kb).c());return ob}function qb(){}qb.prototype=new A;qb.prototype.constructor=qb;qb.prototype.c=function(){return this};
function Xa(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=2147483647<a?2147483647:-2147483648>a?-2147483648:a|0;if(b===a)a=b;else{b=z();var c;if(-9223372036854775808>a)b.ua=-2147483648,c=0;else if(0x7fffffffffffffff<=a)b.ua=2147483647,c=-1;else{c=a|0;var d=a/4294967296|0;b.ua=0>a&&0!==c?-1+d|0:d}b=b.ua;z();a=(0>b?-(4294967296*+((0!==c?~b:-b|0)>>>0)+ +((-c|0)>>>0)):4294967296*b+ +(c>>>0))===a?c^b:va(wa(),a)}return a}return qa(b)?(a=null===b?z().ga:b,b=(new M).E(a.o,a.K),a=b.o,b=b.K,b===
a>>31?a:a^b):sa(b)}qb.prototype.b=y({Tc:0},"scala.runtime.Statics$",{Tc:1,d:1});var rb=void 0;function Ya(){rb||(rb=(new qb).c());return rb}function N(){}N.prototype=new A;N.prototype.constructor=N;N.prototype.c=function(){return this};
function sb(a,b){if(b.hasAttribute("itemtype")&&"http://schema.org/Recipe"===b.getAttribute("itemtype"))return!0;var c=b.children;if(0!==(c.length|0)){var d=c.length|0,g=0>=d;if(g)var k=0;else b=d>>31,k=(0===b?-1<(-2147483648^d):0<b)?-1:d;var m=-1+d|0;tb||(tb=(new O).c());ub();tb||(tb=(new O).c());vb();b=(new wb).c();if(0>k)throw xb||(xb=(new yb).c()),(new I).B("0 until "+d+" by 1: seqs cannot contain more than Int.MaxValue elements.");if(!g)for(d=0;;){k=c.item(d);g=b;if(g.H>=g.Y.a.length){var t=
32+g.V|0,e=g,u=t,F=g.V^t;if(1024>F)1===e.p()&&(e.i(r(D(B),[32])),e.e().a[0]=e.k(),e.D(1+e.p()|0)),e.j(r(D(B),[32])),e.e().a[31&u>>5]=e.k();else if(32768>F)2===e.p()&&(e.l(r(D(B),[32])),e.f().a[0]=e.e(),e.D(1+e.p()|0)),e.j(r(D(B),[32])),e.i(r(D(B),[32])),e.e().a[31&u>>5]=e.k(),e.f().a[31&u>>10]=e.e();else if(1048576>F)3===e.p()&&(e.n(r(D(B),[32])),e.g().a[0]=e.f(),e.D(1+e.p()|0)),e.j(r(D(B),[32])),e.i(r(D(B),[32])),e.l(r(D(B),[32])),e.e().a[31&u>>5]=e.k(),e.f().a[31&u>>10]=e.e(),e.g().a[31&u>>15]=
e.f();else if(33554432>F)4===e.p()&&(e.w(r(D(B),[32])),e.m().a[0]=e.g(),e.D(1+e.p()|0)),e.j(r(D(B),[32])),e.i(r(D(B),[32])),e.l(r(D(B),[32])),e.n(r(D(B),[32])),e.e().a[31&u>>5]=e.k(),e.f().a[31&u>>10]=e.e(),e.g().a[31&u>>15]=e.f(),e.m().a[31&u>>20]=e.g();else if(1073741824>F)5===e.p()&&(e.Z(r(D(B),[32])),e.x().a[0]=e.m(),e.D(1+e.p()|0)),e.j(r(D(B),[32])),e.i(r(D(B),[32])),e.l(r(D(B),[32])),e.n(r(D(B),[32])),e.w(r(D(B),[32])),e.e().a[31&u>>5]=e.k(),e.f().a[31&u>>10]=e.e(),e.g().a[31&u>>15]=e.f(),e.m().a[31&
u>>20]=e.g(),e.x().a[31&u>>25]=e.m();else throw(new I).c();g.V=t;g.H=0}g.Y.a[g.H]=k;g.H=1+g.H|0;if(d===m)break;d=1+d|0}c=b.V+b.H|0;0===c?b=vb().La:(m=(new zb).Fa(0,c,0),Ma(m,b,b.X),1<b.X&&La(m,0,-1+c|0),b=m);b=Ab(b);for(c=!1;!c&&b.Q;)c=b.O(),c=sb(a,c);return c}return!1}N.prototype.main=function(){var a=sb,b=Qa();0===(268435456&b.A)&&0===(268435456&b.A)&&(b.eb=Oa(b).document,b.A|=268435456);a(this,b.eb.body)?Oa(Qa()).alert("Hooray! This looks like a recipe!!!"):Oa(Qa()).alert("This is not a recipe :(")};
N.prototype.b=y({Bb:0},"com.schwartz.scraper.Scraper$",{Bb:1,d:1,ud:1});var Bb=void 0;n.com=n.com||{};n.com.schwartz=n.com.schwartz||{};n.com.schwartz.scraper=n.com.schwartz.scraper||{};n.com.schwartz.scraper.Scraper=function(){Bb||(Bb=(new N).c());return Bb};function Cb(){}Cb.prototype=new A;Cb.prototype.constructor=Cb;function Db(){}Db.prototype=Cb.prototype;function P(){this.z=null}P.prototype=new A;P.prototype.constructor=P;function Eb(){}Eb.prototype=P.prototype;
P.prototype.hb=function(){if(void 0===l.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=mb(pb(),b),null!==a)if(a&&a.b&&a.b.u.Ha)a=a.J;else throw lb(pb(),a);else throw b;}this.stackdata=a}else l.Error.captureStackTrace(this),this.stackdata=this;return this};P.prototype.Ea=function(){return this.z};P.prototype.s=function(){var a=G(ha(this)),b=this.Ea();return null===b?a:a+": "+b};P.prototype.G=function(a){this.z=a;this.hb();return this};function Fb(){this.Ga=0}Fb.prototype=new Sa;
Fb.prototype.constructor=Fb;Fb.prototype.c=function(){Gb=this;this.Ga=ta(ua(),"Seq");ta(ua(),"Map");ta(ua(),"Set");return this};function Hb(a){var b=Ib(),c;if(a&&a.b&&a.b.u.id){c=0;for(var b=b.Ga,d=a;!d.Wc();)a=d.Vc(),d=d.wd(),b=Ta(b,Xa(Ya(),a)),c=1+c|0;c=Ua(b^c)}else c=Va(b,a,b.Ga);return c}Fb.prototype.b=y({Xb:0},"scala.util.hashing.MurmurHash3$",{Xb:1,cd:1,d:1});var Gb=void 0;function Ib(){Gb||(Gb=(new Fb).c());return Gb}function Q(){}Q.prototype=new fb;Q.prototype.constructor=Q;
function Jb(){}Jb.prototype=Q.prototype;Q.prototype.c=function(){(new Kb).pa(this);return this};function R(){}R.prototype=new A;R.prototype.constructor=R;function Lb(){}Lb.prototype=R.prototype;R.prototype.pa=function(a){if(null===a)throw lb(pb(),null);return this};function Mb(){}Mb.prototype=new A;Mb.prototype.constructor=Mb;function Nb(){}Nb.prototype=Mb.prototype;Mb.prototype.s=function(){return"\x3cfunction1\x3e"};function Ob(){this.q=!1}Ob.prototype=new A;Ob.prototype.constructor=Ob;
Ob.prototype.s=function(){return""+this.q};function bb(){var a=new Ob;a.q=!0;return a}Ob.prototype.b=y({Qc:0},"scala.runtime.BooleanRef",{Qc:1,d:1,h:1});var pa=y({Rc:0},"scala.runtime.BoxedUnit",{Rc:1,d:1,h:1},void 0,void 0,function(a){return void 0===a});function K(){this.q=0}K.prototype=new A;K.prototype.constructor=K;K.prototype.s=function(){return""+this.q};K.prototype.aa=function(a){this.q=a;return this};K.prototype.b=y({Sc:0},"scala.runtime.IntRef",{Sc:1,d:1,h:1});
var oa=y({Gb:0},"java.lang.Boolean",{Gb:1,d:1,h:1,y:1},void 0,void 0,function(a){return"boolean"===typeof a});function S(){this.Ia=0}S.prototype=new A;S.prototype.constructor=S;S.prototype.s=function(){return l.String.fromCharCode(this.Ia)};function Pb(a){var b=new S;b.Ia=a;return b}S.prototype.F=function(){return this.Ia};S.prototype.b=y({Ib:0},"java.lang.Character",{Ib:1,d:1,h:1,y:1});function Qb(){this.z=null}Qb.prototype=new Eb;Qb.prototype.constructor=Qb;function Rb(){}Rb.prototype=Qb.prototype;
function Sb(){}Sb.prototype=new Lb;Sb.prototype.constructor=Sb;Sb.prototype.c=function(){R.prototype.pa.call(this,ub());return this};Sb.prototype.b=y({ic:0},"scala.collection.IndexedSeq$$anon$1",{ic:1,yc:1,d:1,uc:1});function Tb(){}Tb.prototype=new Jb;Tb.prototype.constructor=Tb;function Ub(){}Ub.prototype=Tb.prototype;function Kb(){this.fa=null}Kb.prototype=new Lb;Kb.prototype.constructor=Kb;Kb.prototype.pa=function(a){if(null===a)throw lb(pb(),null);this.fa=a;R.prototype.pa.call(this,a);return this};
Kb.prototype.b=y({xc:0},"scala.collection.generic.GenTraversableFactory$$anon$1",{xc:1,yc:1,d:1,uc:1});function yb(){}yb.prototype=new A;yb.prototype.constructor=yb;yb.prototype.c=function(){return this};yb.prototype.b=y({Dc:0},"scala.collection.immutable.Range$",{Dc:1,d:1,P:1,h:1});var xb=void 0;function Vb(){this.gb=null}Vb.prototype=new Nb;Vb.prototype.constructor=Vb;Vb.prototype.R=function(a){return(0,this.gb)(a)};function Wa(a){var b=new Vb;b.gb=a;return b}
Vb.prototype.b=y({Lc:0},"scala.scalajs.runtime.AnonFunction1",{Lc:1,vd:1,d:1,Ka:1});function Wb(){this.ua=0;this.ga=null}Wb.prototype=new A;Wb.prototype.constructor=Wb;Wb.prototype.c=function(){Xb=this;this.ga=(new M).E(0,0);return this};
function Yb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ba(1E9)|0)-(0!==b?ba(b):32+ba(a)|0)|0,d=c,g=0===(32&d)?1E9<<d:0,d=0===(32&d)?5E8>>>(31-d|0)|0|0<<d:1E9<<d,k=a,m=b;for(a=b=0;0<=c&&0!==(-2097152&m);){var t=k,e=m,u=g,F=d;if(e===F?(-2147483648^t)>=(-2147483648^u):(-2147483648^e)>=(-2147483648^F))t=m,e=d,m=k-g|0,t=(-2147483648^m)>(-2147483648^k)?-1+(t-e|0)|0:t-e|0,k=m,m=t,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;t=d>>>1|0;g=g>>>1|0|d<<31;d=t}c=m;if(0===c?-1147483648<=(-2147483648^
k):-2147483648<=(-2147483648^c))c=4294967296*m+ +(k>>>0),k=c/1E9,g=k/4294967296|0,d=b,b=k=d+(k|0)|0,a=(-2147483648^k)<(-2147483648^d)?1+(a+g|0)|0:a+g|0,k=c%1E9|0;c=""+k;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}Wb.prototype.b=y({Nc:0},"scala.scalajs.runtime.RuntimeLong$",{Nc:1,d:1,P:1,h:1});var Xb=void 0;function z(){Xb||(Xb=(new Wb).c());return Xb}
var ia=y({Db:0},"java.lang.String",{Db:1,d:1,h:1,lb:1,y:1},void 0,void 0,function(a){return"string"===typeof a}),ja=y({Hb:0},"java.lang.Byte",{Hb:1,M:1,d:1,h:1,y:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),na=y({Lb:0},"java.lang.Double",{Lb:1,M:1,d:1,h:1,y:1},void 0,void 0,function(a){return"number"===typeof a}),ma=y({Mb:0},"java.lang.Float",{Mb:1,M:1,d:1,h:1,y:1},void 0,void 0,function(a){return"number"===typeof a}),la=y({Pb:0},"java.lang.Integer",{Pb:1,M:1,d:1,h:1,y:1},void 0,
void 0,function(a){return(a|0)===a&&1/a!==1/-0}),ra=y({Qb:0},"java.lang.Long",{Qb:1,M:1,d:1,h:1,y:1},void 0,void 0,function(a){return qa(a)});function Zb(){this.z=null}Zb.prototype=new Rb;Zb.prototype.constructor=Zb;function T(){}T.prototype=Zb.prototype;var ka=y({Sb:0},"java.lang.Short",{Sb:1,M:1,d:1,h:1,y:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function U(){this.v=null}U.prototype=new A;U.prototype.constructor=U;function cb(a,b){a.v=""+a.v+(null===b?"null":b);return a}
U.prototype.s=function(){return this.v};U.prototype.aa=function(){U.prototype.B.call(this,"");return this};U.prototype.B=function(a){this.v=a;return this};U.prototype.b=y({Tb:0},"java.lang.StringBuilder",{Tb:1,d:1,lb:1,Xc:1,h:1});function V(){}V.prototype=new A;V.prototype.constructor=V;function $b(){}$b.prototype=V.prototype;V.prototype.s=function(){return(this.$()?"non-empty":"empty")+" iterator"};V.prototype.na=function(a){for(;this.$();)a.R(this.O())};
V.prototype.Ma=function(a,b,c,d){return ab(this,a,b,c,d)};function M(){this.K=this.o=0}M.prototype=new Db;M.prototype.constructor=M;f=M.prototype;f.Fa=function(a,b,c){M.prototype.E.call(this,a|b<<22,b>>10|c<<12);return this};f.s=function(){z();var a=this.o,b=this.K;return b===a>>31?""+a:0>b?"-"+Yb(-a|0,0!==a?~b:-b|0):Yb(a,b)};f.E=function(a,b){this.o=a;this.K=b;return this};f.aa=function(a){M.prototype.E.call(this,a,a>>31);return this};f.F=function(){return this.o^this.K};
function qa(a){return!!(a&&a.b&&a.b.u.zb)}f.b=y({zb:0},"scala.scalajs.runtime.RuntimeLong",{zb:1,M:1,d:1,h:1,y:1});function I(){this.z=null}I.prototype=new T;I.prototype.constructor=I;I.prototype.c=function(){P.prototype.G.call(this,null);return this};I.prototype.B=function(a){P.prototype.G.call(this,a);return this};I.prototype.b=y({Nb:0},"java.lang.IllegalArgumentException",{Nb:1,ca:1,ba:1,N:1,d:1,h:1});function W(){this.z=null}W.prototype=new T;W.prototype.constructor=W;
W.prototype.B=function(a){P.prototype.G.call(this,a);return this};W.prototype.b=y({Ob:0},"java.lang.IndexOutOfBoundsException",{Ob:1,ca:1,ba:1,N:1,d:1,h:1});function ac(){this.z=null}ac.prototype=new T;ac.prototype.constructor=ac;ac.prototype.c=function(){P.prototype.G.call(this,null);return this};ac.prototype.b=y({Rb:0},"java.lang.NullPointerException",{Rb:1,ca:1,ba:1,N:1,d:1,h:1});function X(){this.z=null}X.prototype=new T;X.prototype.constructor=X;
X.prototype.B=function(a){P.prototype.G.call(this,a);return this};X.prototype.b=y({Ub:0},"java.util.NoSuchElementException",{Ub:1,ca:1,ba:1,N:1,d:1,h:1});function J(){this.da=this.nb=this.z=null;this.wa=!1}J.prototype=new T;J.prototype.constructor=J;J.prototype.Ea=function(){if(!this.wa&&!this.wa){var a;if(null===this.da)a="null";else try{a=ga(this.da)+" ("+("of class "+G(ha(this.da)))+")"}catch(b){if(null!==mb(pb(),b))a="an instance of class "+G(ha(this.da));else throw b;}this.nb=a;this.wa=!0}return this.nb};
J.prototype.oa=function(a){this.da=a;P.prototype.G.call(this,null);return this};J.prototype.b=y({Vb:0},"scala.MatchError",{Vb:1,ca:1,ba:1,N:1,d:1,h:1});function L(){}L.prototype=new $b;L.prototype.constructor=L;L.prototype.c=function(){return this};L.prototype.O=function(){throw(new X).B("next on empty iterator");};L.prototype.$=function(){return!1};L.prototype.b=y({oc:0},"scala.collection.Iterator$$anon$2",{oc:1,pb:1,d:1,qb:1,ta:1,sa:1});function bc(){}bc.prototype=new Ub;
bc.prototype.constructor=bc;function cc(){}cc.prototype=bc.prototype;function wb(){this.X=this.H=this.V=0;this.bb=this.Za=this.Wa=this.Ta=this.Qa=this.Y=null}wb.prototype=new A;wb.prototype.constructor=wb;f=wb.prototype;f.g=function(){return this.Wa};f.c=function(){this.Y=r(D(B),[32]);this.X=1;this.H=this.V=0;return this};f.p=function(){return this.X};f.Z=function(a){this.bb=a};f.k=function(){return this.Y};f.l=function(a){this.Ta=a};f.m=function(){return this.Za};f.i=function(a){this.Qa=a};
f.w=function(a){this.Za=a};f.e=function(){return this.Qa};f.x=function(){return this.bb};f.D=function(a){this.X=a};f.f=function(){return this.Ta};f.j=function(a){this.Y=a};f.n=function(a){this.Wa=a};f.b=y({Gc:0},"scala.collection.immutable.VectorBuilder",{Gc:1,d:1,Jc:1,Ic:1,Ac:1,vc:1,yb:1});function dc(){this.Da=this.o=this.C=this.Ba=0;this.Q=!1;this.xa=0;this.cb=this.$a=this.Xa=this.Ua=this.Ra=this.za=null}dc.prototype=new $b;dc.prototype.constructor=dc;f=dc.prototype;
f.O=function(){if(!this.Q)throw(new X).B("reached iterator end");var a=this.za.a[this.o];this.o=1+this.o|0;if(this.o===this.Da)if((this.C+this.o|0)<this.Ba){var b=32+this.C|0,c=this.C^b;if(1024>c)this.j(this.e().a[31&b>>5]);else if(32768>c)this.i(this.f().a[31&b>>10]),this.j(this.e().a[0]);else if(1048576>c)this.l(this.g().a[31&b>>15]),this.i(this.f().a[0]),this.j(this.e().a[0]);else if(33554432>c)this.n(this.m().a[31&b>>20]),this.l(this.g().a[0]),this.i(this.f().a[0]),this.j(this.e().a[0]);else if(1073741824>
c)this.w(this.x().a[31&b>>25]),this.n(this.m().a[0]),this.l(this.g().a[0]),this.i(this.f().a[0]),this.j(this.e().a[0]);else throw(new I).c();this.C=b;b=this.Ba-this.C|0;this.Da=32>b?b:32;this.o=0}else this.Q=!1;return a};f.g=function(){return this.Xa};f.p=function(){return this.xa};f.Z=function(a){this.cb=a};f.E=function(a,b){this.Ba=b;this.C=-32&a;this.o=31&a;a=b-this.C|0;this.Da=32>a?a:32;this.Q=(this.C+this.o|0)<b;return this};f.k=function(){return this.za};f.l=function(a){this.Ua=a};f.m=function(){return this.$a};
f.i=function(a){this.Ra=a};f.$=function(){return this.Q};f.w=function(a){this.$a=a};f.e=function(){return this.Ra};f.x=function(){return this.cb};f.D=function(a){this.xa=a};f.f=function(){return this.Ua};f.j=function(a){this.za=a};f.n=function(a){this.Xa=a};f.b=y({Hc:0},"scala.collection.immutable.VectorIterator",{Hc:1,pb:1,d:1,qb:1,ta:1,sa:1,yb:1});function ec(){}ec.prototype=new cc;ec.prototype.constructor=ec;function fc(){}fc.prototype=ec.prototype;function gc(){}gc.prototype=new fc;
gc.prototype.constructor=gc;gc.prototype.c=function(){Q.prototype.c.call(this);hc=this;(new Sb).c();return this};gc.prototype.b=y({hc:0},"scala.collection.IndexedSeq$",{hc:1,vb:1,wb:1,rb:1,sb:1,tb:1,d:1,xb:1,ub:1});var hc=void 0;function ub(){hc||(hc=(new gc).c());return hc}function Y(){this.L=this.Aa=0;this.fa=null}Y.prototype=new $b;Y.prototype.constructor=Y;Y.prototype.O=function(){this.L>=this.Aa&&($a||($a=(new Za).c()),$a.fb.O());var a=this.fa.ja(this.L);this.L=1+this.L|0;return a};
Y.prototype.$=function(){return this.L<this.Aa};Y.prototype.b=y({kc:0},"scala.collection.IndexedSeqLike$Elements",{kc:1,pb:1,d:1,qb:1,ta:1,sa:1,dd:1,P:1,h:1});function O(){}O.prototype=new fc;O.prototype.constructor=O;O.prototype.c=function(){Q.prototype.c.call(this);return this};O.prototype.b=y({Cc:0},"scala.collection.immutable.IndexedSeq$",{Cc:1,vb:1,wb:1,rb:1,sb:1,tb:1,d:1,xb:1,ub:1});var tb=void 0;function nb(){this.J=this.z=null}nb.prototype=new T;nb.prototype.constructor=nb;f=nb.prototype;
f.hb=function(){this.stackdata=this.J;return this};f.Ea=function(){return ga(this.J)};f.oa=function(a){this.J=a;P.prototype.G.call(this,null);return this};f.F=function(){var a;Ib();var b=-889275714;for(a=0;1>a;){Ya();var c;b:switch(a){case 0:c=this.J;break b;default:throw(new W).B(""+a);}b=Ta(b,Xa(0,c));a=1+a|0}a=Ua(b^1);return a};f.b=y({Ha:0},"scala.scalajs.js.JavaScriptException",{Ha:1,ca:1,ba:1,N:1,d:1,h:1,ad:1,ob:1,P:1});function ic(){this.La=null}ic.prototype=new fc;
ic.prototype.constructor=ic;ic.prototype.c=function(){Q.prototype.c.call(this);jc=this;this.La=(new zb).Fa(0,0,0);return this};ic.prototype.b=y({Fc:0},"scala.collection.immutable.Vector$",{Fc:1,vb:1,wb:1,rb:1,sb:1,tb:1,d:1,xb:1,ub:1,P:1,h:1});var jc=void 0;function vb(){jc||(jc=(new ic).c());return jc}function kc(){}kc.prototype=new A;kc.prototype.constructor=kc;function lc(){}lc.prototype=kc.prototype;kc.prototype.Ma=function(a,b,c,d){return ab(this,a,b,c,d)};function mc(){}mc.prototype=new lc;
mc.prototype.constructor=mc;function nc(){}nc.prototype=mc.prototype;mc.prototype.na=function(a){for(var b=this.kb();b.$();)a.R(b.O())};function oc(){}oc.prototype=new nc;oc.prototype.constructor=oc;function pc(){}pc.prototype=oc.prototype;
oc.prototype.s=function(){var a;a:{a=G(ha(this));for(var b=-1+(a.length|0)|0;;)if(-1!==b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;if(-1===b||46===(65535&(a.charCodeAt(b)|0)))a="";else for(var c="";;){for(var d=1+b|0;;)if(-1!==b&&57>=(65535&(a.charCodeAt(b)|0))&&48<=(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;for(var g=b;;)if(-1!==b&&36!==(65535&(a.charCodeAt(b)|0))&&46!==(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var k=1+b|0;if(b===g&&d!==(a.length|0)){a=c;break a}for(;;)if(-1!==
b&&36===(65535&(a.charCodeAt(b)|0)))b=-1+b|0;else break;var g=-1===b?!0:46===(65535&(a.charCodeAt(b)|0)),m;(m=g)||(m=65535&(a.charCodeAt(k)|0),m=!(90<m&&127>m||65>m));if(m){d=a.substring(k,d);k=c;if(null===k)throw(new ac).c();c=""===k?d:""+d+Pb(46)+c;if(g){a=c;break a}}}}a+="(";return this.Ma((new Z).c(),a,", ",")").t.v};function qc(){}qc.prototype=new pc;qc.prototype.constructor=qc;function rc(){}rc.prototype=qc.prototype;
function zb(){this.ma=this.Ca=this.ea=0;this.Oa=!1;this.ya=0;this.db=this.ab=this.Ya=this.Va=this.Sa=this.Pa=null}zb.prototype=new pc;zb.prototype.constructor=zb;f=zb.prototype;f.g=function(){return this.Ya};f.ja=function(a){var b=a+this.ea|0;if(0<=a&&b<this.Ca)a=b;else throw(new W).B(""+a);return Ka(this,a,a^this.ma)};f.p=function(){return this.ya};f.R=function(a){return this.ja(a|0)};f.Fa=function(a,b,c){this.ea=a;this.Ca=b;this.ma=c;this.Oa=!1;return this};f.Z=function(a){this.db=a};f.k=function(){return this.Pa};
f.l=function(a){this.Va=a};f.m=function(){return this.ab};f.kb=function(){return Ab(this)};f.i=function(a){this.Sa=a};f.w=function(a){this.ab=a};f.e=function(){return this.Sa};f.x=function(){return this.db};
function Ab(a){var b=(new dc).E(a.ea,a.Ca);Ma(b,a,a.ya);if(a.Oa){var c=a.ma,d=-1+b.p()|0;switch(d){case 5:b.Z(H(b.x()));b.w(H(b.m()));b.n(H(b.g()));b.l(H(b.f()));b.i(H(b.e()));b.x().a[31&c>>25]=b.m();b.m().a[31&c>>20]=b.g();b.g().a[31&c>>15]=b.f();b.f().a[31&c>>10]=b.e();b.e().a[31&c>>5]=b.k();break;case 4:b.w(H(b.m()));b.n(H(b.g()));b.l(H(b.f()));b.i(H(b.e()));b.m().a[31&c>>20]=b.g();b.g().a[31&c>>15]=b.f();b.f().a[31&c>>10]=b.e();b.e().a[31&c>>5]=b.k();break;case 3:b.n(H(b.g()));b.l(H(b.f()));b.i(H(b.e()));
b.g().a[31&c>>15]=b.f();b.f().a[31&c>>10]=b.e();b.e().a[31&c>>5]=b.k();break;case 2:b.l(H(b.f()));b.i(H(b.e()));b.f().a[31&c>>10]=b.e();b.e().a[31&c>>5]=b.k();break;case 1:b.i(H(b.e()));b.e().a[31&c>>5]=b.k();break;case 0:break;default:throw(new J).oa(d);}}1<b.xa&&La(b,a.ea,a.ea^a.ma);return b}f.F=function(){return Hb(this)};f.D=function(a){this.ya=a};f.f=function(){return this.Va};f.j=function(a){this.Pa=a};f.n=function(a){this.Ya=a};
f.b=y({Ec:0},"scala.collection.immutable.Vector",{Ec:1,Zb:1,Yb:1,$b:1,d:1,sc:1,tc:1,Bc:1,wc:1,ta:1,sa:1,fc:1,pc:1,ec:1,zc:1,lc:1,ac:1,bc:1,mc:1,ob:1,qc:1,Wb:1,Ka:1,cc:1,dc:1,rc:1,gd:1,jd:1,hd:1,ld:1,Zc:1,gc:1,jc:1,yb:1,P:1,h:1,ed:1});function Z(){this.t=null}Z.prototype=new rc;Z.prototype.constructor=Z;f=Z.prototype;f.c=function(){Z.prototype.Eb.call(this,16,"");return this};f.ja=function(a){a=65535&(this.t.v.charCodeAt(a)|0);return Pb(a)};f.R=function(a){a=65535&(this.t.v.charCodeAt(a|0)|0);return Pb(a)};
f.s=function(){return this.t.v};f.na=function(a){for(var b=0,c=this.t.v.length|0;b<c;)a.R(this.ja(b)),b=1+b|0};f.kb=function(){var a=new Y;a.Aa=this.t.v.length|0;if(null===this)throw lb(pb(),null);a.fa=this;a.L=0;return a};f.Eb=function(a,b){Z.prototype.Fb.call(this,cb((new U).aa((b.length|0)+a|0),b));return this};f.Fb=function(a){this.t=a;return this};function db(a,b){var c=a.t;ua();cb(c,null===b?"null":ga(b));return a}f.F=function(){return Hb(this)};
f.b=y({Kc:0},"scala.collection.mutable.StringBuilder",{Kc:1,md:1,Zb:1,Yb:1,$b:1,d:1,sc:1,tc:1,Bc:1,wc:1,ta:1,sa:1,fc:1,pc:1,ec:1,zc:1,lc:1,ac:1,bc:1,mc:1,ob:1,qc:1,Wb:1,Ka:1,cc:1,dc:1,rc:1,rd:1,qd:1,td:1,$c:1,sd:1,nd:1,Yc:1,Kb:1,lb:1,od:1,gc:1,jc:1,pd:1,kd:1,fd:1,bd:1,y:1,Jc:1,Ic:1,Ac:1,vc:1,P:1,h:1});
}).call(this);
//# sourceMappingURL=recipe-scraper-opt.js.map
